"""Storage for the backtesting lab: per-game backfill state, the spots table
every run computes over, and the strategies with their saved parameters.

The two-phase design from .claude/V2-BACKTESTING.md lives here:
  backtest_spots is written ONCE per game by the backfill (slow, MLB replay +
  tick alignment) and holds RAW factors plus a compressed price path. Every
  "Run backtest" is then pure arithmetic over these rows — weights, bounce
  definition, fees and delay are all applied at query time, so parameter
  tweaks re-score history for free and win definitions can be COMPARED
  instead of picked blind.
"""

import json

from backend.database.db import get_db

SCHEMA = """
-- one row per tracked MLB market the backfill has looked at, whatever the
-- outcome — errors are recorded, not retried forever
CREATE TABLE IF NOT EXISTS backtest_games (
    market_id       INTEGER PRIMARY KEY,
    game_pk         INTEGER,
    slug            TEXT,
    gold            INTEGER,             -- 1 = live-collected 1-10s ticks; 0 = minute bars
    mlb_home        TEXT,
    mlb_away        TEXT,
    home_outcome_id INTEGER,
    away_outcome_id INTEGER,
    status          TEXT NOT NULL,       -- done | error:<reason>
    spots           INTEGER NOT NULL DEFAULT 0,
    backfilled_at   TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

-- one row per qualifying moment: a completed half-inning with one side
-- trailing and its price under the WIDE net (45c) — run-time gates narrow
CREATE TABLE IF NOT EXISTS backtest_spots (
    id              INTEGER PRIMARY KEY,
    market_id       INTEGER NOT NULL,
    game_pk         INTEGER NOT NULL,
    gold            INTEGER NOT NULL,
    ts              TEXT NOT NULL,       -- half-inning end (about.endTime, UTC)
    inning          INTEGER NOT NULL,
    next_half       TEXT NOT NULL,       -- 'top' | 'bottom' about to start
    trailing_side   TEXT NOT NULL,       -- MLB 'home' | 'away'
    trailing_is_home INTEGER NOT NULL,
    deficit         INTEGER NOT NULL,
    innings_left    INTEGER NOT NULL,    -- regulation innings still to play
    halves_left     INTEGER NOT NULL,    -- offensive halves the trailer still gets
    entry0          REAL,                -- trailing mid at ts (+15/+30/+60s)
    entry15         REAL,
    entry30         REAL,
    entry60         REAL,
    entry_lag_s     REAL,                -- first tick's lag behind the half end
    factors         TEXT NOT NULL,       -- raw checklist inputs, JSON
    path            TEXT NOT NULL        -- {"1":{"ts","max","at"},..,"6"} JSON
);
CREATE INDEX IF NOT EXISTS idx_backtest_spots_market ON backtest_spots(market_id);

-- Strategy #3: games TIED at the middle of an inning (the away side has just
-- batted, the break is on, the home half is about to start) and what happened
-- next. Needs no tick data — whether a game was level at that moment and who
-- eventually won is pure MLB record — so it covers the whole season, and the
-- version wipe above deliberately does NOT clear it.
CREATE TABLE IF NOT EXISTS backtest_bottom8 (
    game_pk      INTEGER PRIMARY KEY,
    game_date    TEXT NOT NULL,
    away_name    TEXT, home_name TEXT,
    away_abbr    TEXT, home_abbr TEXT,
    -- cumulative runs at the middle of the 7th/8th/9th (away has batted N
    -- times, home N-1). NULL when the game never reached that break.
    mid7_away INTEGER, mid7_home INTEGER,
    mid8_away INTEGER, mid8_home INTEGER,
    mid9_away INTEGER, mid9_home INTEGER,
    final_away   INTEGER NOT NULL,
    final_home   INTEGER NOT NULL,
    final_inning INTEGER NOT NULL,
    winner       TEXT NOT NULL
);

-- one row per swept calendar day; done=0 while any game that day was still
-- in progress, so the day is revisited until every result is in
CREATE TABLE IF NOT EXISTS backtest_bottom8_days (
    day  TEXT PRIMARY KEY,
    done INTEGER NOT NULL DEFAULT 0
);


-- reconstructed Clear Favorite verdicts: the T-5 computation re-run for
-- HISTORICAL games from as-of-then data (timecode boxscores, season
-- schedules sliced to the date, our own pre-game ticks). Real locks live in
-- favorite_verdicts; these carry synthetic=true and are never mixed silently.
CREATE TABLE IF NOT EXISTS backtest_fav_history (
    game_pk    INTEGER PRIMARY KEY,
    market_id  INTEGER NOT NULL,
    t5_ts      TEXT NOT NULL,
    payload    TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);

CREATE TABLE IF NOT EXISTS backtest_strategies (
    id          INTEGER PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    params      TEXT NOT NULL,           -- JSON
    created_at  TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
);
"""

# Bumping this wipes and rebuilds backtest_games/spots on the next deploy —
# they are derived data, regenerated by the backfill job in a few passes.
# v2: tied moments stored (home side, deficit 0) for the Comeback Setup replay.
# v3: entry_lag_s stored — the Aug 14 timestamp audit found 83 spots (2.4%)
#     whose first available tick was minutes after the half end (dead-market
#     stretches); the engine now excludes entries that stale.
SCHEMA_VERSION = 3

# The seeded strategy replays the Comeback Setup TAG (Aug 13's live trigger)
# over the recorded corpus: every param of the tag, adjustable. minInning
# defaults to 8 per the client's "after top 8th" with 7 selectable ("inning
# >= 7, preferably 8" in his first writing).
DEFAULT_PARAMS = {
    "kind": "comeback_replay",
    "situation": {
        "minInning": 8,
        "scoreStates": ["down1", "tied"],   # home down exactly 1 / tied
        "requireHomeNext": True,            # bottom half about to start
    },
    "fatigue": {
        # the replayable stand-ins for "tired reliever": season WHIP, walks
        # this game, pitch count. minMatches 0 = no fatigue filter at all.
        "minMatches": 1,
        "whipAbove": 1.35,
        "minWalksGame": 2,
        "minPitches": 85,
    },
    "bounce": {"targetCents": 5, "horizonHalfInnings": 4, "giveUp": "horizon"},
    "exec": {"delaySeconds": 15, "slippageCentsPerSide": 1.0, "feeMode": "taker_both"},
    "corpus": {"segment": "both"},
    "stake": {"mode": "flat_usd", "usd": 100},
}

# Strategy #2: the Clear Favorite verdicts, exactly as LOCKED ~5 min before
# first pitch, replayed as bets held to settlement. The stored payload keeps
# both sides' full breakdowns, so every threshold below is re-applied at
# query time over the SAME locks — no recomputation, no look-ahead. Redeeming
# a winner is fee-free (the V3 rule), so fees apply to the entry leg only.
FAVORITE_DEFAULTS = {
    "kind": "favorite_replay",
    "filter": {
        "minTotal": 75,            # the client's bar; sweeps show 65/70/80 too
        "minPriceCents": 59,
        "maxPriceCents": 100,
        "requireNoDisqualifiers": True,   # price-related ones are re-checked
        "maxFlags": 1,                    # his rule: 2+ uncertainty flags kill it
        # locked = the real T-5 snapshots (since Aug 13); reconstructed = the
        # historical re-computation with its flagged approximations
        "source": "both",                 # both | locked | reconstructed
    },
    "exec": {"slippageCentsPerSide": 1.0, "entryFee": "taker"},  # taker | maker
    "stake": {"mode": "flat_usd", "usd": 100},
    "corpus": {"segment": "both"},
}

FAVORITE_SEED = (
    "Clear Favorite — hold to win (all season games, no tick data needed)",
    "Replays the verdicts exactly as locked ~5 minutes before first pitch: "
    "back the qualifying side, hold to settlement. Because the score is "
    "computed pre-game, this strategy needs no tick data — coverage is every "
    "final regular-season game since Opening Day, with entry prices from "
    "Polymarket's settled price history and outcomes from MLB finals. "
    "Thresholds are re-applied over the stored verdicts, so every knob "
    "re-scores the same history.")


# Strategy #3 (Aug 20, client): every game TIED at the middle of the 8th —
# away just batted in the top, the break is on, the bottom is about to start —
# replayed over the whole season. The question is the base rate: who actually
# wins from there, and how often it runs past the 9th. The inning is a knob
# (7/8/9) because the same question is worth asking a half-inning either side.
BOTTOM8_DEFAULTS = {
    "kind": "bottom8_replay",
    "situation": {
        "inning": 8,          # tied at the middle of THIS inning
        "side": "home",       # which side the record is kept for
        "extras": "all",      # all | regulation | extras
    },
    # P&L is only possible for games our tick corpus covers; the outcome
    # record covers every game either way.
    "exec": {"slippageCentsPerSide": 1.0, "entryFee": "taker"},
    "stake": {"mode": "flat_usd", "usd": 100},
    "corpus": {"segment": "both"},
}

BOTTOM8_SEED = (
    "Tied entering the bottom 8th (all season games)",
    "Every game level when the top of the 8th ended and the bottom was about "
    "to start, and what happened from there: who won, and how often it ran to "
    "extras. Whether a game was tied at that moment needs no tick data, so "
    "this covers the whole season — prices, where our recorded games supply "
    "them, come from the tick at that exact break.")


# The Aug 5 checklist strategy's defaults — the engine still runs this kind;
# it returns to the page when the client's win definition lands.
CHECKLIST_DEFAULTS = {
    "hardFilters": {
        "maxPriceCents": 25,
        "minPriceCents": 5,
        "minInningsLeft": 4,      # DRAFT — client never fixed the number
        "maxDeficit": 3,
        "side": "both",           # both | home | away (trailing side)
    },
    "bounce": {
        "targetCents": 5,         # DRAFT
        "horizonHalfInnings": 4,  # DRAFT
        "giveUp": "horizon",      # horizon = exit at horizon price | stake = full loss
    },
    "useScore": True,
    "minScore": 7,
    "weights": {
        "remainingInnings": 2,
        "scoreDeficit": 2,
        "trailingTeamHome": 1.5,
        "teamQualityForm": 2,     # factor UNKNOWN in v1 backfill (see replay.py)
        "leadingPitcher": 1.5,
        "trailingPitcher": 1.5,
        "dueUpOrder": 1,
        "parkWeather": 1,
        "priceVsHistory": 1,      # factor UNKNOWN in v1 (needs the WE table)
        "contactBonus": 0.5,
    },
    "exec": {
        "delaySeconds": 15,       # 0 | 15 | 30 | 60 — the stored grid
        "slippageCentsPerSide": 1.0,
        "feeMode": "taker_both",  # taker_both | maker_exit | maker_both
    },
    "corpus": {"segment": "both"},  # gold | silver | both
    "stake": {"mode": "flat_usd", "usd": 100},
}


SEED_DESCRIPTION = (
    "Replays the Comeback Setup tag over every recorded game: home team down 1 "
    "or tied, bottom of the 8th (or your inning) about to start, tired away "
    "pitcher — buy home, exit on the bounce.")


def init():
    with get_db() as conn:
        conn.executescript(SCHEMA)
        # v3 column on a table created under v2 (IF NOT EXISTS won't add it)
        cols = [r["name"] for r in conn.execute("PRAGMA table_info(backtest_spots)")]
        if "entry_lag_s" not in cols:
            conn.execute("ALTER TABLE backtest_spots ADD COLUMN entry_lag_s REAL")
        conn.execute("CREATE TABLE IF NOT EXISTS backtest_meta "
                     "(id INTEGER PRIMARY KEY CHECK (id=1), version INTEGER)")
        row = conn.execute("SELECT version FROM backtest_meta WHERE id=1").fetchone()
        if not row or row["version"] != SCHEMA_VERSION:
            # derived data: wipe, let the backfill job rebuild
            conn.execute("DELETE FROM backtest_spots")
            conn.execute("DELETE FROM backtest_games")
            conn.execute("INSERT INTO backtest_meta (id, version) VALUES (1, ?) "
                         "ON CONFLICT(id) DO UPDATE SET version=excluded.version",
                         (SCHEMA_VERSION,))
        seeded = conn.execute("SELECT id, params FROM backtest_strategies").fetchall()
        if not seeded:
            conn.execute(
                "INSERT INTO backtest_strategies (name, description, params) VALUES (?, ?, ?)",
                ("Potential comeback", SEED_DESCRIPTION, json.dumps(DEFAULT_PARAMS)))
        else:
            # migration: pre-kind rows were the checklist draft — the user
            # replaced that strategy with the tag replay (Aug 14)
            for r in seeded:
                try:
                    p = json.loads(r["params"])
                except json.JSONDecodeError:
                    p = {}
                if "kind" not in p:
                    conn.execute(
                        "UPDATE backtest_strategies SET params=?, description=? WHERE id=?",
                        (json.dumps(DEFAULT_PARAMS), SEED_DESCRIPTION, r["id"]))
        # strategy #2 (Aug 14): the Clear Favorite locks, once
        kinds = [json.loads(r["params"]).get("kind")
                 for r in conn.execute("SELECT params FROM backtest_strategies")]
        if "favorite_replay" not in kinds:
            conn.execute(
                "INSERT INTO backtest_strategies (name, description, params) VALUES (?, ?, ?)",
                (*FAVORITE_SEED, json.dumps(FAVORITE_DEFAULTS)))
        if "bottom8_replay" not in kinds:
            conn.execute(
                "INSERT INTO backtest_strategies (name, description, params) VALUES (?, ?, ?)",
                (*BOTTOM8_SEED, json.dumps(BOTTOM8_DEFAULTS)))
        else:
            # Aug 14 rename: the title now carries the scope parenthetical —
            # this strategy covers the whole season, not just tracked games
            for r in conn.execute("SELECT id, name, params FROM backtest_strategies"):
                if (json.loads(r["params"]).get("kind") == "favorite_replay"
                        and r["name"] != FAVORITE_SEED[0]):
                    conn.execute(
                        "UPDATE backtest_strategies SET name=?, description=? WHERE id=?",
                        (*FAVORITE_SEED, r["id"]))


# ---- backfill bookkeeping -------------------------------------------------

# A market tracked BEFORE its game finishes gets backfilled too early: there
# is no play-by-play yet, so it fails — and because errors are never retried
# it stayed out of the corpus forever. That single cause accounted for 77 of
# 83 failures (25% of the corpus), including games recorded hours earlier the
# same day. It is retried ONCE, well after the game must have ended; a game
# that genuinely has no play-by-play then keeps a terminal status and is left
# alone. Every other error still waits for a human, as before.
# The retry must wait for the GAME, not for the clock: a market tracked well
# in advance was first attempted (and failed) more than 12h before its own
# first pitch, so a time-since-attempt rule retried it while the game still
# had not been played and then wrote it off permanently. The slug carries the
# game date, so the honest test is "that day is over".
RETRY_STATUS = "error:no play-by-play"


def games_pending(min_ticks: int, limit: int) -> list[dict]:
    """Tracked MLB markets with real ticks that the backfill has not finished.
    Genuine errors are NOT retried automatically — they carry their reason and
    wait for a human. The one exception is the "backfilled before the game was
    over" case above, which is re-attempted once."""
    with get_db() as conn:
        return [dict(r) for r in conn.execute(
            """SELECT m.id AS market_id, e.slug,
                      COALESCE(bg.status, '') AS prev_status
               FROM markets m
               JOIN events e ON e.id = m.event_id
               LEFT JOIN backtest_games bg ON bg.market_id = m.id
               WHERE e.slug LIKE 'mlb-%'
                 AND (bg.market_id IS NULL
                      OR (bg.status = ? AND substr(e.slug, -10) < date('now')))
                 AND (SELECT COALESCE(SUM(tc.n), 0) FROM outcomes o
                      JOIN tick_counts tc ON tc.outcome_id = o.id
                      WHERE o.market_id = m.id) >= ?
               ORDER BY m.id LIMIT ?""",
            (RETRY_STATUS, min_ticks, limit))]


def save_game(market_id: int, status: str, *, game_pk=None, slug=None, gold=None,
              mlb_home=None, mlb_away=None, home_outcome_id=None,
              away_outcome_id=None, spots=0):
    with get_db() as conn:
        conn.execute(
            """INSERT INTO backtest_games
                   (market_id, game_pk, slug, gold, mlb_home, mlb_away,
                    home_outcome_id, away_outcome_id, status, spots)
               VALUES (?,?,?,?,?,?,?,?,?,?)
               ON CONFLICT(market_id) DO UPDATE SET
                   game_pk=excluded.game_pk, slug=excluded.slug,
                   gold=excluded.gold, mlb_home=excluded.mlb_home,
                   mlb_away=excluded.mlb_away,
                   home_outcome_id=excluded.home_outcome_id,
                   away_outcome_id=excluded.away_outcome_id,
                   status=excluded.status, spots=excluded.spots,
                   backfilled_at=strftime('%Y-%m-%dT%H:%M:%SZ','now')""",
            (market_id, game_pk, slug, gold, mlb_home, mlb_away,
             home_outcome_id, away_outcome_id, status, spots))


def insert_spots(rows: list[dict]):
    if not rows:
        return
    with get_db() as conn:
        conn.executemany(
            """INSERT INTO backtest_spots
                   (market_id, game_pk, gold, ts, inning, next_half,
                    trailing_side, trailing_is_home, deficit, innings_left,
                    halves_left, entry0, entry15, entry30, entry60,
                    entry_lag_s, factors, path)
               VALUES (:market_id, :game_pk, :gold, :ts, :inning, :next_half,
                       :trailing_side, :trailing_is_home, :deficit,
                       :innings_left, :halves_left, :entry0, :entry15,
                       :entry30, :entry60, :entry_lag_s, :factors, :path)""",
            rows)


def clear_game(market_id: int):
    """Remove a game's spots before re-backfilling it, so a retry can never
    double-count."""
    with get_db() as conn:
        conn.execute("DELETE FROM backtest_spots WHERE market_id=?", (market_id,))
        conn.execute("DELETE FROM backtest_games WHERE market_id=?", (market_id,))


def backfill_summary() -> dict:
    with get_db() as conn:
        done = conn.execute(
            "SELECT COUNT(*) c, COALESCE(SUM(spots),0) s FROM backtest_games "
            "WHERE status='done'").fetchone()
        errors = [dict(r) for r in conn.execute(
            "SELECT market_id, slug, status FROM backtest_games "
            "WHERE status != 'done' ORDER BY market_id DESC LIMIT 20")]
        golds = conn.execute(
            "SELECT COUNT(*) c FROM backtest_games WHERE status='done' AND gold=1"
        ).fetchone()
    return {"games_done": done["c"], "gold_games": golds["c"],
            "spots": done["s"], "recent_errors": errors}


def all_spots(segment: str = "both") -> list[dict]:
    """Every stored spot, oldest first — the run engine's working set. A few
    thousand small rows: loading them wholesale is faster than being clever."""
    where = "" if segment == "both" else f"WHERE gold={1 if segment == 'gold' else 0}"
    with get_db() as conn:
        rows = conn.execute(
            f"SELECT * FROM backtest_spots {where} ORDER BY ts").fetchall()
    out = []
    for r in rows:
        d = dict(r)
        d["factors"] = json.loads(d["factors"])
        d["path"] = json.loads(d["path"])
        out.append(d)
    return out


def bottom8_rows() -> list[dict]:
    """Every recorded tied-at-the-break game, oldest first."""
    with get_db() as conn:
        return [dict(r) for r in conn.execute(
            "SELECT * FROM backtest_bottom8 ORDER BY game_date, game_pk")]


def bottom8_prices(inning: int) -> dict[int, float]:
    """game_pk -> the HOME price at that inning's break, for games the tick
    corpus covers. The spots table already stores a tied half-inning end with
    its aligned first tick, so this costs nothing extra and needs no new
    alignment logic."""
    with get_db() as conn:
        return {r["game_pk"]: r["entry0"] for r in conn.execute(
            """SELECT game_pk, entry0 FROM backtest_spots
               WHERE inning=? AND next_half='bottom' AND deficit=0
                 AND entry0 IS NOT NULL AND trailing_is_home=1""", (inning,))}


def save_bottom8(rows: list[dict]):
    if not rows:
        return
    with get_db() as conn:
        conn.executemany(
            """INSERT OR REPLACE INTO backtest_bottom8
               (game_pk, game_date, away_name, home_name, away_abbr, home_abbr,
                mid7_away, mid7_home, mid8_away, mid8_home, mid9_away, mid9_home,
                final_away, final_home, final_inning, winner)
               VALUES (:game_pk, :game_date, :away_name, :home_name, :away_abbr,
                       :home_abbr, :mid7_away, :mid7_home, :mid8_away, :mid8_home,
                       :mid9_away, :mid9_home, :final_away, :final_home,
                       :final_inning, :winner)""", rows)


def bottom8_days_done() -> set[str]:
    with get_db() as conn:
        return {r["day"] for r in conn.execute(
            "SELECT day FROM backtest_bottom8_days WHERE done=1")}


def mark_bottom8_day(day: str, done: bool):
    with get_db() as conn:
        conn.execute(
            "INSERT INTO backtest_bottom8_days (day, done) VALUES (?, ?) "
            "ON CONFLICT(day) DO UPDATE SET done=excluded.done",
            (day, 1 if done else 0))


def market_matchups() -> dict[int, str]:
    """market_id -> 'Away @ Home', for the spots CSV export."""
    with get_db() as conn:
        return {r["market_id"]: f"{r['mlb_away']} @ {r['mlb_home']}"
                for r in conn.execute(
                    "SELECT market_id, mlb_away, mlb_home FROM backtest_games "
                    "WHERE mlb_away IS NOT NULL AND mlb_home IS NOT NULL")}


def fav_history_rows() -> list[dict]:
    """Reconstructed T-5 verdicts, same joined shape as favorite_locks() plus
    source='reconstructed' and the stored T-5 prices.

    LEFT JOIN: market_id=0 marks games outside the tick corpus (the score
    needs no ticks — entry prices came from CLOB's settled 10-min bars and
    the outcome from MLB's final, both already in the payload)."""
    out = []
    with get_db() as conn:
        for r in conn.execute(
                """SELECT h.game_pk, h.t5_ts, h.payload, h.market_id,
                          g.gold, g.home_outcome_id, g.away_outcome_id
                   FROM backtest_fav_history h
                   LEFT JOIN backtest_games g ON g.market_id = h.market_id
                   ORDER BY h.t5_ts"""):
            try:
                v = json.loads(r["payload"])
            except json.JSONDecodeError:
                continue
            out.append({
                "game_pk": r["game_pk"], "locked_at": r["t5_ts"], "verdict": v,
                "market_id": r["market_id"], "gold": r["gold"],
                "home_outcome_id": r["home_outcome_id"],
                "away_outcome_id": r["away_outcome_id"],
                "source": "reconstructed",
            })
    return out


def save_fav_history(game_pk: int, market_id: int, t5_ts: str, payload: dict):
    with get_db() as conn:
        conn.execute(
            "INSERT OR REPLACE INTO backtest_fav_history (game_pk, market_id, t5_ts, payload) "
            "VALUES (?, ?, ?, ?)",
            (game_pk, market_id, t5_ts, json.dumps(payload)))


def fav_history_pending(limit: int = 500) -> list[dict]:
    with get_db() as conn:
        return [dict(r) for r in conn.execute(
            """SELECT market_id, game_pk, home_outcome_id, away_outcome_id,
                      mlb_home, mlb_away, gold
               FROM backtest_games
               WHERE status='done' AND game_pk IS NOT NULL
                 AND game_pk NOT IN (SELECT game_pk FROM backtest_fav_history)
               ORDER BY market_id LIMIT ?""", (limit,))]


def favorite_locks() -> list[dict]:
    """The locked Clear Favorite verdicts joined to their tracked market, so
    each side has an outcome id (entry price) and a settlement. Only games we
    hold ticks for can be replayed; the rest are counted, not silently lost."""
    out = []
    with get_db() as conn:
        for r in conn.execute(
                "SELECT game_pk, locked_at, payload FROM favorite_verdicts "
                "ORDER BY locked_at"):
            try:
                v = json.loads(r["payload"])
            except json.JSONDecodeError:
                continue
            g = conn.execute(
                """SELECT market_id, gold, home_outcome_id, away_outcome_id
                   FROM backtest_games WHERE game_pk=? AND status='done'""",
                (r["game_pk"],)).fetchone()
            out.append({
                "game_pk": r["game_pk"], "locked_at": r["locked_at"],
                "verdict": v,
                "market_id": g["market_id"] if g else None,
                "gold": g["gold"] if g else None,
                "home_outcome_id": g["home_outcome_id"] if g else None,
                "away_outcome_id": g["away_outcome_id"] if g else None,
                "source": "locked",
            })
    return out


def tick_price_at(outcome_id: int, ts: str,
                  max_lag_s: float = 300.0) -> float | None:
    """The mid at/after a moment, refused if the first tick is too stale —
    the same honesty rule the spots table enforces via entry_lag_s."""
    from datetime import datetime

    def parse(t):
        return datetime.fromisoformat(t.replace("Z", "+00:00")).timestamp()
    with get_db() as conn:
        r = conn.execute(
            "SELECT ts, price FROM ticks WHERE outcome_id=? AND ts>=? "
            "ORDER BY ts LIMIT 1", (outcome_id, ts)).fetchone()
    if not r or parse(r["ts"]) - parse(ts) > max_lag_s:
        return None
    return r["price"]


def home_settlements() -> dict[int, bool | None]:
    """market_id -> did the HOME side win, read from the market's own
    settlement: a finished market's last stored tick is pinned near 100 or 0
    (the V2 rule). None = not decidable from the data."""
    out: dict[int, bool | None] = {}
    with get_db() as conn:
        for r in conn.execute(
                "SELECT market_id, home_outcome_id FROM backtest_games "
                "WHERE status='done' AND home_outcome_id IS NOT NULL"):
            t = conn.execute(
                "SELECT price FROM ticks WHERE outcome_id=? ORDER BY ts DESC LIMIT 1",
                (r["home_outcome_id"],)).fetchone()
            if not t:
                out[r["market_id"]] = None
            elif t["price"] >= 90:
                out[r["market_id"]] = True
            elif t["price"] <= 10:
                out[r["market_id"]] = False
            else:
                out[r["market_id"]] = None
    return out


# ---- strategies -----------------------------------------------------------

def strategies() -> list[dict]:
    with get_db() as conn:
        rows = conn.execute(
            "SELECT id, name, description, params FROM backtest_strategies ORDER BY id"
        ).fetchall()
    return [{**dict(r), "params": json.loads(r["params"])} for r in rows]


def save_params(strategy_id: int, params: dict) -> bool:
    with get_db() as conn:
        cur = conn.execute(
            "UPDATE backtest_strategies SET params=? WHERE id=?",
            (json.dumps(params), strategy_id))
        return cur.rowcount == 1
